version: '3'
services:
  app:
    build: .
    volumes:
      - ./app:/var/www

  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./app/static:/usr/share/nginx/html/static
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www

  composer:
    image: composer
    command: install
    volumes:
      - ./app:/app

  db:
    image: mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./data/db/mysql:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
