version: '3'
services:
  app:
    image: php:7
    command: php -S 0.0.0.0:8000 /app/index.php
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  composer:
    image: composer/composer:php7
    command: install
    volumes:
      - .:/app

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./data/db/mysql:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
